name: logreg_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - jupyterlab
  - notebook
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - ipykernel
  - pytest
  - pip
  - pip:
      - seaborn
